package game.dna.traits;

import game.dna.stats.StatType;

import java.util.Map;

/**
 * Generated by reading trait_to_creature_stat_definitions.json and used to set the values of a creature's stats
 */
public class CreatureStatModifier {

	Map<StatType, Object> statModifiers;

	public Map<StatType, Object> getStatModifiers() {
		return statModifiers;
	}

	public void setStatModifiers(Map<StatType, Object> statModifiers) {
		this.statModifiers = statModifiers;
	}
}
